name: terraform-monorepo-action
description: Returns paths to Terraform modules.
author: DREST LTD
inputs:
  token:
    description: GitHub token. Defaults to secrets.GITHUB_TOKEN.
    required: false
    default: ${{ github.token }}
  mode:
    description: Set to `all` to return all modules or `changed` to only return modules that have changes in this PR/commit. Defaults to `changed`.
    required: false
    default: changed
  includes:
    description: List of module path globs to include. Uses gitignore spec.
    required: false
  ignore:
    description: List of module path globs to ignore. Uses gitignore spec.
    required: false
  monitored:
    description: List of file extensions or base file names to monitor
    required: false
    default: '.tf, .tpl, .yaml, .yml, .terraform.lock.hcl'
outputs:
  modules:
    description: An array of paths to Terraform modules.
runs:
  using: 'node20'
  main: 'dist/index.js'
